%token LET INTERFACE STRUCT ENUM UNION FN IF ELSE RETURN
%token EQUALS
%token <string> IDENT
%token EOF
%token LBRACE LPAREN
%token RBRACE RPAREN
%token COMMA
%token COLON RARROW SEMICOLON
%token TILDE DOT
%token <Z.t> INT

%%
